/**
 * Page assembler — turns a ComicScript + image map into a PDF or a real
 * CBZ (zip archive) of panel images.
 *
 * PDF: uses pdfkit, one page per comic page, panels arranged per `layoutPage()`,
 *      speech-bubble and caption overlays drawn as text on a white bar.
 * CBZ: writes a valid ZIP archive (store mode, no compression) containing
 *      panel images and a `ComicInfo.xml`-shaped cover file.
 */

import PDFDocument from 'pdfkit';
import { createWriteStream, unlinkSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { ComicScript, Page } from '../types.js';
import { layoutPage } from './layouts.js';

export interface AssembleOptions {
  outputPath: string;
  format: 'pdf' | 'cbz';
}

export async function assembleComic(
  script: ComicScript,
  images: Map<string, Buffer>,
  options: AssembleOptions
): Promise<string> {
  await mkdir(dirname(options.outputPath), { recursive: true });
  if (options.format === 'pdf') {
    return assemblePDF(script, images, options.outputPath);
  }
  return assembleCBZ(script, images, options.outputPath);
}

function assemblePDF(
  script: ComicScript,
  images: Map<string, Buffer>,
  outputPath: string
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      layout: 'portrait',
      margin: 36,
    });
    const stream = createWriteStream(outputPath);
    doc.pipe(stream);
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', (err) => {
      // Clean up the partial file so the next attempt doesn't read a 0-byte PDF.
      try { doc.end(); } catch { /* already ended */ }
      try { unlinkSync(outputPath); } catch { /* may not exist yet */ }
      reject(err);
    });

    // Render the body in a try/catch so a renderPage() throw still calls
    // doc.end() and unlinks a partial file. Without this, a malformed
    // page leaves a half-written PDF on disk and the FD open.
    try {
      // --- Title page ---
      doc.fontSize(28).text(script.title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Art style: ${script.artStyle}`, { align: 'center' });
      doc.moveDown(2);
      doc.fontSize(10).text(`Generated by comic-creator (OpenClaw skill)`, { align: 'center' });
      doc.addPage();

      // --- Comic pages ---
      for (let i = 0; i < script.pages.length; i++) {
        const page = script.pages[i];
        renderPage(doc, page, images);
        if (i < script.pages.length - 1) doc.addPage();
      }
      doc.end();
    } catch (err) {
      try { doc.end(); } catch { /* already ended */ }
      try { unlinkSync(outputPath); } catch { /* may not exist yet */ }
      reject(err);
    }
  });
}

function renderPage(
  doc: PDFKit.PDFDocument,
  page: Page,
  images: Map<string, Buffer>
): void {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const margin = 36;
  const geo = layoutPage(page, pageWidth, pageHeight, margin);

  for (const rect of geo.panels) {
    const panel = page.panels[rect.panelIndex];
    if (!panel) continue;

    // Draw panel border
    doc.save();
    doc.lineWidth(1.5).rect(rect.x, rect.y, rect.w, rect.h).stroke();

    // Draw the image (with a small inset so the border stays visible).
    // We do a manual "cover" scale + center-crop: parse the source
    // image's pixel dimensions from its header, scale to fully fill the
    // cell (overflow on one axis), then translate so the visible region
    // is centered. This avoids the letterbox look that pdfkit's
    // `fit: [w, h]` produces when the source aspect doesn't match the
    // cell aspect — a 16:9 image in a 1:1 cell would otherwise be a
    // tiny horizontal strip with empty space top and bottom.
    const buf = images.get(panel.id);
    if (buf && buf.length > 0) {
      try {
        const dims = peekImageDimensions(buf);
        if (dims) {
          const cellW = rect.w - 4;
          const cellH = rect.h - 4;
          const scale = Math.max(cellW / dims.w, cellH / dims.h);
          const drawW = dims.w * scale;
          const drawH = dims.h * scale;
          const offsetX = (cellW - drawW) / 2;
          const offsetY = (cellH - drawH) / 2;
          doc.image(buf, rect.x + 2 + offsetX, rect.y + 2 + offsetY, {
            width: drawW,
            height: drawH,
          });
        } else {
          // Unknown format — fall back to fit-contain.
          doc.image(buf, rect.x + 2, rect.y + 2, {
            width: rect.w - 4,
            height: rect.h - 4,
            fit: [rect.w - 4, rect.h - 4],
            align: 'center',
            valign: 'center',
          });
        }
      } catch (e) {
        doc.fontSize(8).fillColor('#888').text('(image render failed)', rect.x + 4, rect.y + 4);
        doc.fillColor('black');
      }
    } else {
      doc.fontSize(8).fillColor('#888').text('(no image)', rect.x + 4, rect.y + 4);
      doc.fillColor('black');
    }
    doc.restore();

    // Overlay: caption box (white) or first speech bubble near bottom of panel
    const overlayY = rect.y + rect.h - 14;
    const overlayX = rect.x + 4;
    const overlayW = rect.w - 8;
    const text = panel.caption ?? panel.dialogue?.[0];
    if (text) {
      doc.save();
      doc.fontSize(7).fillColor('white').rect(overlayX, overlayY - 2, overlayW, 12).fill();
      doc
        .fillColor('black')
        .text(text, overlayX + 2, overlayY, { width: overlayW - 4, ellipsis: true });
      doc.restore();
    }
  }
}

/**
 * Build a real .cbz (zip) archive. CBZ is just a ZIP containing page
 * images and metadata — readers like YACReader, Komga, and CDisplay
 * expect an actual zip. We write a STORE-only (no compression) zip with
 * standard local-file-header + central-directory entries. STORE is
 * enough because the panel images are already compressed (PNG/JPEG).
 *
 * Format reference: APPNOTE.TXT 6.3.4.
 */
async function assembleCBZ(
  script: ComicScript,
  images: Map<string, Buffer>,
  outputPath: string
): Promise<string> {
  await mkdir(dirname(outputPath), { recursive: true });

  // Collect the entries we'll write. Cover first, then panels in order.
  const entries: Array<{ name: string; data: Buffer }> = [
    { name: '00-cover.txt', data: Buffer.from(
      `${script.title}\nArt style: ${script.artStyle}\nGenerated by comic-creator (OpenClaw skill)\n`,
      'utf8'
    ) },
  ];
  for (const page of script.pages) {
    for (const panel of page.panels) {
      const buf = images.get(panel.id);
      if (!buf) continue;
      const isJpg = buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff;
      const ext = isJpg ? 'jpg' : 'png';
      entries.push({ name: `${panel.id}.${ext}`, data: buf });
    }
  }

  // Write the archive. We assemble all bytes in memory then flush — CBZs
  // are typically 2-10 MB which is fine.
  const chunks: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const e of entries) {
    const nameBuf = Buffer.from(e.name, 'utf8');
    const crc = crc32(e.data);
    const size = e.data.length;
    // Local file header (30 bytes + name)
    const lfh = Buffer.alloc(30);
    lfh.writeUInt32LE(0x04034b50, 0);     // signature
    lfh.writeUInt16LE(20, 4);              // version needed
    lfh.writeUInt16LE(0, 6);               // flags
    lfh.writeUInt16LE(0, 8);               // method = 0 (store)
    lfh.writeUInt16LE(0, 10);              // mod time
    lfh.writeUInt16LE(0, 12);              // mod date
    lfh.writeUInt32LE(crc, 14);            // crc32
    lfh.writeUInt32LE(size, 18);           // compressed size
    lfh.writeUInt32LE(size, 22);           // uncompressed size
    lfh.writeUInt16LE(nameBuf.length, 26); // name length
    lfh.writeUInt16LE(0, 28);              // extra length
    chunks.push(lfh, nameBuf, e.data);

    // Central directory entry (46 bytes + name)
    const cdh = Buffer.alloc(46);
    cdh.writeUInt32LE(0x02014b50, 0);      // signature
    cdh.writeUInt16LE(20, 4);              // version made by
    cdh.writeUInt16LE(20, 6);              // version needed
    cdh.writeUInt16LE(0, 8);               // flags
    cdh.writeUInt16LE(0, 10);              // method
    cdh.writeUInt16LE(0, 12);              // mod time
    cdh.writeUInt16LE(0, 14);              // mod date
    cdh.writeUInt32LE(crc, 16);            // crc32
    cdh.writeUInt32LE(size, 20);           // compressed size
    cdh.writeUInt32LE(size, 24);           // uncompressed size
    cdh.writeUInt16LE(nameBuf.length, 28); // name length
    cdh.writeUInt16LE(0, 30);              // extra length
    cdh.writeUInt16LE(0, 32);              // comment length
    cdh.writeUInt16LE(0, 34);              // disk number
    cdh.writeUInt16LE(0, 36);              // internal attrs
    cdh.writeUInt32LE(0, 38);              // external attrs
    cdh.writeUInt32LE(offset, 42);         // local header offset
    central.push(cdh, nameBuf);

    offset += 30 + nameBuf.length + size;
  }

  // End of central directory record
  const cdOffset = offset;
  const cdSize = central.reduce((s, b) => s + b.length, 0);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);       // signature
  eocd.writeUInt16LE(0, 4);                // disk number
  eocd.writeUInt16LE(0, 6);                // disk with cd
  eocd.writeUInt16LE(entries.length, 8);   // entries on this disk
  eocd.writeUInt16LE(entries.length, 10);  // total entries
  eocd.writeUInt32LE(cdSize, 12);          // cd size
  eocd.writeUInt32LE(cdOffset, 16);        // cd offset
  eocd.writeUInt16LE(0, 20);                // comment length

  await writeFile(outputPath, Buffer.concat([...chunks, ...central, eocd]));
  return outputPath;
}

/**
 * Peek at the first ~64 bytes of an image buffer to extract its
 * pixel dimensions. Supports PNG (via the IHDR chunk) and JPEG
 * (scan for SOF0/SOF2 markers). Returns null if the format is
 * unrecognized — caller falls back to a best-effort fit.
 *
 * We only need the dimensions, so we never decode the image. Cheap
 * to call per panel.
 */
function peekImageDimensions(buf: Buffer): { w: number; h: number } | null {
  if (buf.length < 16) return null;
  // PNG: 89 50 4E 47 0D 0A 1A 0A, then IHDR length (4) "IHDR" (4),
  // then width (4 BE) height (4 BE).
  if (
    buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47 &&
    buf[4] === 0x0d && buf[5] === 0x0a && buf[6] === 0x1a && buf[7] === 0x0a
  ) {
    const w = buf.readUInt32BE(16);
    const h = buf.readUInt32BE(20);
    if (w > 0 && h > 0) return { w, h };
  }
  // JPEG: 0xFF 0xD8 0xFF then a marker. SOF0/SOF1/SOF2/SOF3/SOF5..SOF15
  // all carry the image dimensions in their payload. The marker length
  // (2 bytes BE) and the data segment follow; height is at offset +5
  // and width at offset +7 from the start of the segment data.
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) {
    let i = 2;
    while (i < buf.length - 9) {
      if (buf[i] !== 0xff) {
        i++;
        continue;
      }
      // Skip fill bytes (0xFF padding).
      while (i < buf.length && buf[i] === 0xff) i++;
      if (i >= buf.length) break;
      const marker = buf[i];
      i++;
      // SOI (0xD8), TEM (0x01), RST0-7 (0xD0-0xD7), and standalone
      // markers have no length segment.
      const isStandalone =
        marker === 0x01 ||
        (marker >= 0xd0 && marker <= 0xd9) ||
        marker === 0x00;
      if (isStandalone) continue;
      if (i + 1 >= buf.length) break;
      const segLen = buf.readUInt16BE(i);
      if (segLen < 2) break;
      // SOF0..SOF3, SOF5..SOF7, SOF9..SOF11, SOF13..SOF15 all
      // carry dimensions. Bits 0-3 of the marker nibble tell us
      // which SOF — but 0xC0-0xCF except 0xC4 and 0xC8 are SOF.
      const isSof =
        (marker >= 0xc0 && marker <= 0xcf) &&
        marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
      if (isSof && i + 7 < buf.length) {
        // Precision (1) + height (2 BE) + width (2 BE)
        const h = buf.readUInt16BE(i + 3);
        const w = buf.readUInt16BE(i + 5);
        if (w > 0 && h > 0) return { w, h };
      }
      i += segLen;
    }
  }
  return null;
}

/** Standard CRC-32 used by ZIP. Polynomial 0xEDB88320, init 0xFFFFFFFF. */
const CRC_TABLE: number[] = (() => {
  const t: number[] = new Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf: Buffer): number {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) {
    c = (c >>> 8) ^ CRC_TABLE[(c ^ buf[i]) & 0xFF];
  }
  return (c ^ 0xFFFFFFFF) >>> 0;
}
