/**
 * Page assembler — turns a ComicScript + image map into a PDF or a real
 * CBZ (zip archive) of panel images.
 *
 * PDF: uses pdfkit, one page per comic page, panels arranged per `layoutPage()`,
 *      speech-bubble and caption overlays drawn as text on a white bar.
 * CBZ: writes a valid ZIP archive (store mode, no compression) containing
 *      panel images and a `ComicInfo.xml`-shaped cover file.
 */

import PDFDocument from 'pdfkit';
import { createWriteStream, unlinkSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { ComicScript, Page } from '../types.js';
import { layoutPage } from './layouts.js';

export interface AssembleOptions {
  outputPath: string;
  format: 'pdf' | 'cbz';
}

export async function assembleComic(
  script: ComicScript,
  images: Map<string, Buffer>,
  options: AssembleOptions
): Promise<string> {
  await mkdir(dirname(options.outputPath), { recursive: true });
  if (options.format === 'pdf') {
    return assemblePDF(script, images, options.outputPath);
  }
  return assembleCBZ(script, images, options.outputPath);
}

function assemblePDF(
  script: ComicScript,
  images: Map<string, Buffer>,
  outputPath: string
): Promise<string> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      layout: 'portrait',
      margin: 36,
    });
    const stream = createWriteStream(outputPath);
    doc.pipe(stream);
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', (err) => {
      // Clean up the partial file so the next attempt doesn't read a 0-byte PDF.
      try { doc.end(); } catch { /* already ended */ }
      try { unlinkSync(outputPath); } catch { /* may not exist yet */ }
      reject(err);
    });

    // Render the body in a try/catch so a renderPage() throw still calls
    // doc.end() and unlinks a partial file. Without this, a malformed
    // page leaves a half-written PDF on disk and the FD open.
    try {
      // --- Title page ---
      doc.fontSize(28).text(script.title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Art style: ${script.artStyle}`, { align: 'center' });
      doc.moveDown(2);
      doc.fontSize(10).text(`Generated by comic-creator (OpenClaw skill)`, { align: 'center' });
      doc.addPage();

      // --- Comic pages ---
      for (let i = 0; i < script.pages.length; i++) {
        const page = script.pages[i];
        renderPage(doc, page, images);
        if (i < script.pages.length - 1) doc.addPage();
      }
      doc.end();
    } catch (err) {
      try { doc.end(); } catch { /* already ended */ }
      try { unlinkSync(outputPath); } catch { /* may not exist yet */ }
      reject(err);
    }
  });
}

function renderPage(
  doc: PDFKit.PDFDocument,
  page: Page,
  images: Map<string, Buffer>
): void {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const margin = 36;
  const geo = layoutPage(page, pageWidth, pageHeight, margin);

  for (const rect of geo.panels) {
    const panel = page.panels[rect.panelIndex];
    if (!panel) continue;

    // Draw panel border
    doc.save();
    doc.lineWidth(1.5).rect(rect.x, rect.y, rect.w, rect.h).stroke();

    // Draw the image (with a small inset so the border stays visible)
    const buf = images.get(panel.id);
    if (buf && buf.length > 0) {
      try {
        doc.image(buf, rect.x + 2, rect.y + 2, {
          width: rect.w - 4,
          height: rect.h - 4,
          fit: [rect.w - 4, rect.h - 4],
        });
      } catch (e) {
        doc.fontSize(8).fillColor('#888').text('(image render failed)', rect.x + 4, rect.y + 4);
        doc.fillColor('black');
      }
    } else {
      doc.fontSize(8).fillColor('#888').text('(no image)', rect.x + 4, rect.y + 4);
      doc.fillColor('black');
    }
    doc.restore();

    // Overlay: caption box (white) or first speech bubble near bottom of panel
    const overlayY = rect.y + rect.h - 14;
    const overlayX = rect.x + 4;
    const overlayW = rect.w - 8;
    const text = panel.caption ?? panel.dialogue?.[0];
    if (text) {
      doc.save();
      doc.fontSize(7).fillColor('white').rect(overlayX, overlayY - 2, overlayW, 12).fill();
      doc
        .fillColor('black')
        .text(text, overlayX + 2, overlayY, { width: overlayW - 4, ellipsis: true });
      doc.restore();
    }
  }
}

/**
 * Build a real .cbz (zip) archive. CBZ is just a ZIP containing page
 * images and metadata — readers like YACReader, Komga, and CDisplay
 * expect an actual zip. We write a STORE-only (no compression) zip with
 * standard local-file-header + central-directory entries. STORE is
 * enough because the panel images are already compressed (PNG/JPEG).
 *
 * Format reference: APPNOTE.TXT 6.3.4.
 */
async function assembleCBZ(
  script: ComicScript,
  images: Map<string, Buffer>,
  outputPath: string
): Promise<string> {
  await mkdir(dirname(outputPath), { recursive: true });

  // Collect the entries we'll write. Cover first, then panels in order.
  const entries: Array<{ name: string; data: Buffer }> = [
    { name: '00-cover.txt', data: Buffer.from(
      `${script.title}\nArt style: ${script.artStyle}\nGenerated by comic-creator (OpenClaw skill)\n`,
      'utf8'
    ) },
  ];
  for (const page of script.pages) {
    for (const panel of page.panels) {
      const buf = images.get(panel.id);
      if (!buf) continue;
      const isJpg = buf.length >= 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff;
      const ext = isJpg ? 'jpg' : 'png';
      entries.push({ name: `${panel.id}.${ext}`, data: buf });
    }
  }

  // Write the archive. We assemble all bytes in memory then flush — CBZs
  // are typically 2-10 MB which is fine.
  const chunks: Buffer[] = [];
  const central: Buffer[] = [];
  let offset = 0;
  for (const e of entries) {
    const nameBuf = Buffer.from(e.name, 'utf8');
    const crc = crc32(e.data);
    const size = e.data.length;
    // Local file header (30 bytes + name)
    const lfh = Buffer.alloc(30);
    lfh.writeUInt32LE(0x04034b50, 0);     // signature
    lfh.writeUInt16LE(20, 4);              // version needed
    lfh.writeUInt16LE(0, 6);               // flags
    lfh.writeUInt16LE(0, 8);               // method = 0 (store)
    lfh.writeUInt16LE(0, 10);              // mod time
    lfh.writeUInt16LE(0, 12);              // mod date
    lfh.writeUInt32LE(crc, 14);            // crc32
    lfh.writeUInt32LE(size, 18);           // compressed size
    lfh.writeUInt32LE(size, 22);           // uncompressed size
    lfh.writeUInt16LE(nameBuf.length, 26); // name length
    lfh.writeUInt16LE(0, 28);              // extra length
    chunks.push(lfh, nameBuf, e.data);

    // Central directory entry (46 bytes + name)
    const cdh = Buffer.alloc(46);
    cdh.writeUInt32LE(0x02014b50, 0);      // signature
    cdh.writeUInt16LE(20, 4);              // version made by
    cdh.writeUInt16LE(20, 6);              // version needed
    cdh.writeUInt16LE(0, 8);               // flags
    cdh.writeUInt16LE(0, 10);              // method
    cdh.writeUInt16LE(0, 12);              // mod time
    cdh.writeUInt16LE(0, 14);              // mod date
    cdh.writeUInt32LE(crc, 16);            // crc32
    cdh.writeUInt32LE(size, 20);           // compressed size
    cdh.writeUInt32LE(size, 24);           // uncompressed size
    cdh.writeUInt16LE(nameBuf.length, 28); // name length
    cdh.writeUInt16LE(0, 30);              // extra length
    cdh.writeUInt16LE(0, 32);              // comment length
    cdh.writeUInt16LE(0, 34);              // disk number
    cdh.writeUInt16LE(0, 36);              // internal attrs
    cdh.writeUInt32LE(0, 38);              // external attrs
    cdh.writeUInt32LE(offset, 42);         // local header offset
    central.push(cdh, nameBuf);

    offset += 30 + nameBuf.length + size;
  }

  // End of central directory record
  const cdOffset = offset;
  const cdSize = central.reduce((s, b) => s + b.length, 0);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);       // signature
  eocd.writeUInt16LE(0, 4);                // disk number
  eocd.writeUInt16LE(0, 6);                // disk with cd
  eocd.writeUInt16LE(entries.length, 8);   // entries on this disk
  eocd.writeUInt16LE(entries.length, 10);  // total entries
  eocd.writeUInt32LE(cdSize, 12);          // cd size
  eocd.writeUInt32LE(cdOffset, 16);        // cd offset
  eocd.writeUInt16LE(0, 20);                // comment length

  await writeFile(outputPath, Buffer.concat([...chunks, ...central, eocd]));
  return outputPath;
}

/** Standard CRC-32 used by ZIP. Polynomial 0xEDB88320, init 0xFFFFFFFF. */
const CRC_TABLE: number[] = (() => {
  const t: number[] = new Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf: Buffer): number {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) {
    c = (c >>> 8) ^ CRC_TABLE[(c ^ buf[i]) & 0xFF];
  }
  return (c ^ 0xFFFFFFFF) >>> 0;
}
