import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const pkg = JSON.parse(await readFile('package.json', 'utf8')) as {
  scripts?: Record<string, string>;
};
const readme = await readFile('README.md', 'utf8');
const startCommand = await readFile('start.command', 'utf8');
const debugHtml = await readFile('webui/__test__.html', 'utf8');
const appJs = await readFile('webui/app.js', 'utf8');
const generateButton = await readFile('webui/components/GenerateButton.js', 'utf8');
const historyPanel = await readFile('webui/components/History.js', 'utf8');
const optionsPanel = await readFile('webui/components/OptionsPanel.js', 'utf8');
const settingsPanel = await readFile('webui/components/Settings.js', 'utf8');
const moviePanel = await readFile('webui/components/MoviePanel.js', 'utf8');
const resultPanel = await readFile('webui/components/ResultPanel.js', 'utf8');
const cliSource = await readFile('src/cli.ts', 'utf8');
const serverReadme = await readFile('src/server/README.md', 'utf8');
const externalGuide = await readFile('docs/agents/external-agent-guide.md', 'utf8');
const playbook = await readFile('docs/agents/hermes-openclaw-playbook.md', 'utf8');
const mcpServer = await readFile('src/mcp/server.ts', 'utf8');

assert.equal(pkg.scripts?.start, 'tsx src/server/index.ts');
assert.equal(startCommand.includes('npm start'), true);
assert.equal(startCommand.includes('dist/server/index.js'), false);
assert.equal(readme.includes('| `projectPath` |'), true);
assert.equal(readme.includes('| `agentPlaybookPath` |'), true);
assert.equal(readme.includes('| `agentWorkflowPackagePath` |'), true);
assert.equal(readme.includes('| `screenplayPath` |'), true);
assert.equal(readme.includes('| `directorBriefPath` |'), true);
assert.equal(readme.includes('| `storyboardPackagePath` |'), true);
assert.equal(readme.includes('| `seriesPackagePath` |'), true);
assert.equal(readme.includes('| `trailerPackagePath` |'), true);
assert.equal(readme.includes('| `videoPackagePath` |'), true);
assert.equal(readme.includes('| `animaticTimelinePath` |'), true);
assert.equal(readme.includes('| `songSheetPath` |'), true);
assert.equal(readme.includes('| `musicCuePackagePath` |'), true);
assert.equal(readme.includes('| `songAudioPath` |'), true);
assert.equal(readme.includes('| `studioBundlePath` |'), true);
assert.equal(readme.includes('Markdown handoff'), true);
assert.equal(readme.includes('docs/agents/hermes-openclaw-playbook.md'), true);
assert.equal(readme.includes('get_agent_playbook'), true);
assert.equal(readme.includes('get_agent_workflow_package'), true);
assert.equal(readme.includes('get_studio_bundle'), true);
assert.equal(readme.includes('get_music_cue_package'), true);
assert.equal(readme.includes('--agent-playbook'), true);
assert.equal(readme.includes('--json'), true);
assert.equal(readme.includes('--studio-bundle'), true);
assert.equal(readme.includes('--agent-workflow-package'), true);
assert.equal(readme.includes('--screenplay'), true);
assert.equal(readme.includes('--director-brief'), true);
assert.equal(readme.includes('--video-package'), true);
assert.equal(readme.includes('--series-package'), true);
assert.equal(readme.includes('--trailer-package'), true);
assert.equal(readme.includes('--music-cue-package'), true);
assert.equal(readme.includes('--project-goal'), true);
assert.equal(readme.includes('save a default project goal'), true);
assert.equal(readme.includes('When `screen` is selected'), true);
assert.equal(readme.includes('unified studio bundle'), true);
assert.equal(readme.includes('External agents should start from the studio bundle first'), true);
assert.equal(readme.includes('MCP provider fields are registry-based, not hard-coded'), true);
assert.equal(readme.includes('WebUI-created custom OpenAI-compatible providers'), true);
assert.equal(readme.includes('get_music_cue_package'), true);
assert.equal(readme.includes('get_screenplay'), true);
assert.equal(readme.includes('get_director_brief'), true);
assert.equal(readme.includes('get_series_package'), true);
assert.equal(readme.includes('get_trailer_package'), true);
assert.equal(readme.includes('get_video_package'), true);
assert.equal(readme.includes('agentPlaybookPath'), true);
assert.equal(readme.includes('agentWorkflowPackagePath'), true);
assert.equal(readme.includes('Movie / Show tab with pitch, trailer, story, series, script, shots, previs, timeline, music, agents, and deliverables tabs'), true);
assert.equal(playbook.includes('## Task Routing'), true);
assert.equal(playbook.includes('## Agent Loop'), true);
assert.equal(playbook.includes('studioBundlePath'), true);
assert.equal(playbook.includes('minimax'), true);
assert.equal(externalGuide.includes('agentPlaybookPath'), true);
assert.equal(externalGuide.includes('agentWorkflowPackagePath'), true);
assert.equal(externalGuide.includes('screenplayPath'), true);
assert.equal(externalGuide.includes('directorBriefPath'), true);
assert.equal(externalGuide.includes('musicCuePackagePath'), true);
assert.equal(externalGuide.includes('seriesPackagePath'), true);
assert.equal(externalGuide.includes('trailerPackagePath'), true);
assert.equal(externalGuide.includes('videoPackagePath'), true);
assert.equal(debugHtml.includes('Array.isArray(b.music)'), true);
assert.equal(generateButton.includes('Timed out waiting for comic to finish.'), false);
assert.equal(historyPanel.includes('Download the unified studio bundle for this history item'), true);
assert.equal(historyPanel.includes('history-cover-img'), true);
assert.equal(historyPanel.includes('/api/comic/${entry.jobId}/cover'), true);
assert.equal(historyPanel.includes('studio-bundle'), true);
assert.equal(historyPanel.includes('bundle.artifactPaths?.projectPath ?? null'), true);
assert.equal(historyPanel.includes('bundle.format === \'studio-bundle\''), true);
assert.equal(historyPanel.includes('Goal: '), true);
assert.equal(historyPanel.includes('Download the repo-level Hermes/OpenClaw playbook'), true);
assert.equal(historyPanel.includes('Download the Hermes/OpenClaw workflow package for this history item'), true);
assert.equal(historyPanel.includes('Download the music cue package for this history item'), true);
assert.equal(historyPanel.includes('Download the episodic series package for this history item'), true);
assert.equal(historyPanel.includes('Download the screenplay for this history item'), true);
assert.equal(historyPanel.includes('Download the director brief for this history item'), true);
assert.equal(historyPanel.includes('Download the MiniMax-ready video package for this history item'), true);
assert.equal(moviePanel.includes('Movie / Show Board'), true);
assert.equal(moviePanel.includes('This is the adaptation workspace'), true);
assert.equal(moviePanel.includes('storyboardPrompts.map'), true);
assert.equal(moviePanel.includes('movie-journey'), true);
assert.equal(moviePanel.includes('movie-deliverables'), true);
assert.equal(moviePanel.includes('Pitch'), true);
assert.equal(moviePanel.includes('Script'), true);
assert.equal(moviePanel.includes('Previs'), true);
assert.equal(moviePanel.includes('Timeline'), true);
assert.equal(moviePanel.includes('Deliverables'), true);
assert.equal(moviePanel.includes('Agents'), true);
assert.equal(moviePanel.includes('movie-trailer-beats'), true);
assert.equal(moviePanel.includes('movie-previs-list'), true);
assert.equal(moviePanel.includes('Trailer'), true);
assert.equal(moviePanel.includes('Series'), true);
assert.equal(moviePanel.includes('Series hook'), true);
assert.equal(moviePanel.includes('Episode seeds'), true);
assert.equal(moviePanel.includes('Screenplay export'), true);
assert.equal(moviePanel.includes('Download screenplay'), true);
assert.equal(moviePanel.includes('Director brief'), true);
assert.equal(moviePanel.includes('Video generation package'), true);
assert.equal(moviePanel.includes('Trailer package'), true);
assert.equal(moviePanel.includes('Download ${item.label.toLowerCase()}'), true);
assert.equal(moviePanel.includes('Download music package'), true);
assert.equal(moviePanel.includes('Hermes / OpenClaw workspace'), true);
assert.equal(moviePanel.includes('Download workflow package'), true);
assert.equal(moviePanel.includes('Operator checklist'), true);
assert.equal(moviePanel.includes('Agent deliverables'), true);
assert.equal(moviePanel.includes('result-tabs movie-tabs'), true);
assert.equal(moviePanel.includes('Download playbook'), true);
assert.equal(appJs.includes('Movie / Show'), true);
assert.equal(appJs.includes('Comic Studio'), true);
assert.equal(appJs.includes('Comic Reader'), true);
assert.equal(optionsPanel.includes('Project goal'), true);
assert.equal(optionsPanel.includes('project-goal'), true);
assert.equal(optionsPanel.includes('Screen projects default to the storyboard widescreen profile'), true);
assert.equal(settingsPanel.includes('Default project goal'), true);
assert.equal(settingsPanel.includes('default-project-goal'), true);
assert.equal(settingsPanel.includes('Use this to bias new runs'), true);
assert.equal(appJs.includes('defaultProjectGoal'), true);
assert.equal(resultPanel.includes('Download agent playbook'), true);
assert.equal(resultPanel.includes('Download agent workflow package'), true);
assert.equal(resultPanel.includes('Download studio bundle'), true);
assert.equal(resultPanel.includes('Download theme audio'), true);
assert.equal(resultPanel.includes('Download music cue package'), true);
assert.equal(resultPanel.includes('Download series package'), true);
assert.equal(resultPanel.includes('Download screenplay'), true);
assert.equal(resultPanel.includes('Download director brief'), true);
assert.equal(resultPanel.includes('Download video package'), true);
assert.equal(resultPanel.includes('Open movie board'), true);
assert.equal(resultPanel.includes('Goal: '), true);
assert.equal(resultPanel.includes('Project Assets'), true);
assert.equal(resultPanel.includes('Comic Reader'), true);
assert.equal(resultPanel.includes('Panel pages'), true);
assert.equal(resultPanel.includes('PDF preview'), true);
assert.equal(resultPanel.includes('scrollIntoView'), true);
assert.equal(readme.includes('Comic Reader with a panel-page view'), true);
assert.equal(readme.includes('Refreshed studio theme'), true);
assert.equal(cliSource.includes('--project-goal=<name>'), true);
assert.equal(cliSource.includes('renderProfile: project.renderProfile'), true);
assert.equal(mcpServer.includes("projectGoal: z"), true);
assert.equal(serverReadme.includes('defaultProjectGoal'), true);
assert.equal(serverReadme.includes('agentPlaybookPath'), true);
assert.equal(serverReadme.includes('agentWorkflowPackagePath'), true);
assert.equal(serverReadme.includes('screenplayPath'), true);
assert.equal(serverReadme.includes('directorBriefPath'), true);
assert.equal(serverReadme.includes('seriesPackagePath'), true);
assert.equal(serverReadme.includes('trailerPackagePath'), true);
assert.equal(serverReadme.includes('videoPackagePath'), true);
assert.equal(serverReadme.includes('/api/agent-playbook'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/pdf'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/cbz'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/cover'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/project'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/agent-guidance'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/screenplay'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/agent-workflow-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/director-brief'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/storyboard-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/music-cue-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/song-sheet'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/theme-audio'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/series-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/trailer-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/video-package'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/animatic-timeline'), true);
assert.equal(serverReadme.includes('/api/comic/:jobId/studio-bundle'), true);

const toolNames = [...mcpServer.matchAll(/server\.tool\(\s*['"]([^'"]+)['"]/g)].map((match) => match[1]);
const toolsLine = readme.split('\n').find((line) => line.startsWith('Tools: ')) ?? '';
for (const toolName of toolNames) {
  assert.equal(
    toolsLine.includes(`\`${toolName}\``),
    true,
    `README MCP tool list is missing ${toolName}`
  );
}

console.log('PASS docs contract');
